# Generated by Django 2.0 on 2019-03-22 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20190322_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='zip',
        ),
    ]
